### ISSUE TITLE
¿How make a public file after to upload?

### ISSUE THREAD

**Issue by NeftaliAcosta** [keithweaver/python-aws-s3#1]
![image](https://user-images.githubusercontent.com/15948880/50789060-c7e07280-1280-11e9-803d-cd2c6777678e.png)

I use my s3 cube as a cdn for my project. But every time I upload a file I have to make it public manually.
What do I need to do for everyone?
Thank you

**Comment by jschwarzwalder** [comment]
responded on the [awsdocs/aws-doc-sdk-examples](https://github.com/awsdocs/aws-doc-sdk-examples/issues/377) repo

**Comment by umairnsr87** [comment]
AWS_DEFAULT_ACL = 'public-read' use this statement in your python file and add some permissions n actions which are mentioned below.

"Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:PutObjectAcl"
            ]

This is the resolution if anyone faces this problem again instead of going through the docs.
